# Generated by Django 5.2.4 on 2025-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blotter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blotterreport',
            old_name='statement',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blotterreport',
            name='evidence',
        ),
        migrations.AddField(
            model_name='blotterreport',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blotterreport',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blotterreport',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blotterreport',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Varies', 'Varies')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='blotterreport',
            name='witnesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blotterreport',
            name='incident_type',
            field=models.CharField(choices=[('Noise Complaint', 'Noise Complaint'), ('Theft/Burglary', 'Theft/Burglary'), ('Neighbor Dispute', 'Neighbor Dispute'), ('Traffic Violation', 'Traffic Violation'), ('Property Damage', 'Property Damage'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blotterreport',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blotterreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=30),
        ),
    ]
