# Generated by Django 5.1.7 on 2025-10-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blotter', '0002_rename_statement_blotterreport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blotterreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
