# Generated by Django 5.2.4 on 2025-08-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_latitude_alter_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='complaint_evidence/'),
        ),
        migrations.DeleteModel(
            name='ComplaintEvidence',
        ),
    ]
