# Generated by Django 5.2.4 on 2025-08-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_businesspermit'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='certificate_type',
            field=models.CharField(max_length=50),
        ),
    ]
