# Generated by Django 5.2.4 on 2025-08-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_certificaterequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('owner_address', models.TextField()),
                ('business_description', models.TextField(blank=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
