# Generated by Django 5.2.4 on 2025-08-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_businesspermit_user_alter_certificaterequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
