# Generated by Django 5.2.4 on 2025-08-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_businesspermit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
