# Generated by Django 5.2.4 on 2025-08-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_alter_businesspermit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
