# Generated by Django 5.1.7 on 2025-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_businesspermit_housenum_certificaterequest_housenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=50, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
