# Generated by Django 5.1.7 on 2025-10-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_certificatecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
