# Generated by Django 5.1.7 on 2025-10-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='houseNum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
