# Generated by Django 5.2.4 on 2025-08-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_emergencyreport_report_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyreport',
            old_name='emergency_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='report_number',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='reporter',
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='incident_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('medical', 'Medical'), ('security', 'Security'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='emergency_media/'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='EmergencyFeedback',
        ),
    ]
