# Generated by Django 5.2.4 on 2025-08-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_rename_emergency_type_emergencyreport_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
