# Generated by Django 5.2.4 on 2025-08-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_emergencyreport_latitude_emergencyreport_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
    ]
