# Generated by Django 5.2.4 on 2025-08-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0009_alter_emergencyreport_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
