# Generated by Django 5.1.7 on 2025-10-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0013_alter_emergencyalert_alert_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert_message',
            field=models.TextField(default='🚨 Emergency reported. Stay alert.'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='alert_message',
            field=models.TextField(default='🚨 Emergency reported. Stay alert.'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='media_file',
            field=models.FileField(upload_to='emergency_media/'),
        ),
    ]
