# Generated by Django 5.2.7 on 2025-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0014_alter_emergencyalert_alert_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='media_file',
            field=models.URLField(),
        ),
    ]
