# Generated by Django 5.2.7 on 2025-10-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0016_remove_emergencyreport_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='media_url',
        ),
    ]
