# Generated by Django 5.2.7 on 2025-10-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0017_remove_emergencyreport_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='media_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
