# Generated by Django 5.2.7 on 2025-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0018_emergencyreport_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='media_url',
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='media_file',
            field=models.FileField(default='', upload_to='emergency_media/'),
        ),
    ]
