# Generated by Django 5.2.7 on 2025-10-20 12:01

import emergency.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0020_alter_emergencyreport_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='media_file',
            field=models.FileField(blank=True, null=True, storage=emergency.storages.SupabaseStorage, upload_to='emergency_media/'),
        ),
    ]
