# Generated by Django 5.2.4 on 2025-08-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_priority_complaint_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
