# Generated by Django 5.2.4 on 2025-08-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_alter_emergencyreport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
