# Generated by Django 5.2.4 on 2025-08-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0012_emergencyreport_alert_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert_message',
            field=models.TextField(default='Emergency reported. Stay alert.'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='alert_message',
            field=models.TextField(default='Emergency reported. Stay alert.'),
        ),
    ]
