# Generated by Django 5.2.7 on 2025-10-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0015_alter_emergencyreport_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='media_file',
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='media_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
