# Generated by Django 5.1.7 on 2025-10-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_alter_businesspermit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='houseNum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='houseNum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
